### ISSUE TITLE
load flight mission failed

### ISSUE THREAD

**Issue by Czw007** [BlackJocker1995/uavga#1]
I recently reproduced your article 2022-ICSE-LGdFuzzer. In your paper, you did a comparative experiment with the 2019-Usenix-RVFuzzer paper. As far as I know, RVFuzzer is not open source. Do you reproduce it yourself? , or obtained the source code from the original author.

**Comment by BlackJocker1995** [comment]
The RVFuzzer compared in our paper mainly involves its two search methods, namely One and Multiple, both of which are publicized in the original text of RVFuzzer, which are essentially two Binary Search.
So we reproduced their search method. However, it should be noted that our paper does not refer to the Control Instability Detector in RVFuzzer. We define a instability occurred when real physical problems appear, so we did not implement the part of RVFuzzer on the Detector. In fact, the Detector is their previous work which call Control Invariant. You can refer their previous article Detecting Attacks Against Robotic Vehicles: A Control Invariant Approach to understand the principle. Essentially Invariant is an input-output fitting model, which can be achieved by non-linear fitting methods.


[BlackJocker1995/uavga] load flight mission failed (Issue #1)


I recently reproduced your article 2022-ICSE-LGdFuzzer. In your paper, you did a comparative experiment with the 2019-Usenix-RVFuzzer paper. As far as I know, RVFuzzer is not open source. Do you reproduce it yourself? , or obtained the source code from the original author.

**Comment by Czw007** [comment]
@BlackJocker1995 ，This solved my doubts, thanks a lot.
