### ISSUE TITLE
Questions about state predictor

### ISSUE THREAD

**Issue by Czw007** [BlackJocker1995/uavga#3]
您好！在看了您的论文后，我存在以下几点疑惑，劳烦您在百忙之中可以给出回复！
1）在3.3节，您提到ML predictor可以预测下一个时间戳的参考状态（the next reference state），飞控软件的控制算法也可以预测参考状态，请问这两个参考状态有什么区别呢？
2）另外您提到使用预测器就不需要实际/模拟执行无人机，也能判断配置是否会导致无人机出现不稳定状态。对于一个配置，如果不模拟/实际执行，那么无人机的状态、传感器状态都是初始化状态，通过这些初始化的数据就可以预测无人机是否会出现不稳定的状态吗？
3）参数的安全范围和执行任务密切相关，并且看到您的代码中只有一个飞行任务文件，请问您是只对一个飞行任务做了测试吗？
非常希望能得到您的解答！非常感谢！

**Comment by BlackJocker1995** [comment]
1) 飞控算法给出的 reference state 是多层级的，无法引入一些参数对飞行的影响，例如任务参数。我们使用predictor来抽象了飞控自身的预测模型，并引入了其他参数，相当于将中间飞控程序程序具体的预测流程进行了抽象处理。
2）使用预测器是进行预测判断，用于概率引导配置进行突变。相当于输出预测的反馈，当然，这种预测可能会存在偏差， 但是趋势预测大体方向是正确的。GA过程会从历史的飞行数据中提取飞行状态，通过迭代来产生会大概率（也就是predictor预测的大概率）使这些状态出现问题的配置，最终会通过模拟器来验证这个配置的影响。
3) 模拟测试只使用了一种任务。
