### ISSUE TITLE
When the function mav_monitor_error() performed?

### ISSUE THREAD

**Issue by mapleLeaves111** [BlackJocker1995/uavga#4]
Excuse me, Is the drone error detection (function mav_monitor_error ()) performed at the same time as the drone's mission or after the mission is completed? See you're using a multithreaded approach, does that mean that the flight mission and error detection are going on at the same time?

**Comment by BlackJocker1995** [comment]
The **mav_monitor** in the **manager** is another thread that runs the STIL simulator. 
**mav_monitor_error** is a loop program in the main thread that uses mavlink to monitor the flight status of the drone.
