### ISSUE TITLE
遗传算法部分的一个问题

### ISSUE THREAD

**Issue by Czw007** [BlackJocker1995/uavga#5]
![image](https://user-images.githubusercontent.com/54148853/179656254-110b935c-cf96-4954-9f95-43e09b97dff0.png)

**Comment by BlackJocker1995** [comment]
context segment是不变的，每次变化的是其中的configuration。

**Comment by Czw007** [comment]
我是这样理解的，从理论上来说context segment应该是需要变化的，但假定不变并不会影响结果，因为搜索的目的是找到潜在的不正确的配置，并且在下一步中会逐一验证每个配置，筛选出不正确的配置。我的理解是虽然这个预测过程在理论上并不能完全说的通，但是这对搜索结果没有影响，即找到2036个配置错误。

**Comment by BlackJocker1995** [comment]
我们针对了多个不同的context segment进行搜索，所以context是变的，还有，github issues提供程序上问题的修复，论文内容请直接发邮件咨询。

**Comment by Czw007** [comment]
好的！非常感谢您的回答！
